### PR TITLE
Update to support HTTP/knative invocations

### PR DESCRIPTION
**Pull request by matthewmcnew**
This PR updates the python3 invoker to support http based invocations for python functions.

Before these changes work with `riff function create` on the riff cli a new version of the function invoker docker image needs to be pushed and the riff cli needs to be updated to support python. 

In the meantime, the README is updated with simple instructions on building a docker image and pushing with `riff service create`.

A sample of this working is available at:  https://github.com/matthewmcnew/python-function

Feedback welcome!

### CODE REVIEW

**Comment by matthewmcnew** [comment]
It looks like travis is failing on the old docs workflow.

I'll create a PR to update this and remove the docs steps similar to: https://github.com/projectriff/command-function-invoker/commit/4ef98280c27aef748adffed83d7da4547a969ca3#diff-b67911656ef5d18c4ae36cb6741b7965.

**Comment by matthewmcnew** [comment]
Travis should pass with these changes: https://github.com/projectriff/python3-function-invoker/pull/12.

**Comment by matthewmcnew** [comment]
Hi @fbiville ,

I believe this is the result of the referenced python function (https://github.com/fbiville/python-function) not supporting JSON inputs and is throwing an exception. 

The following should work:
```bash
riff service invoke python-upper --text -- -d 'hi pythong'
```

The json input would work on a function that supports json such as: https://github.com/projectriff/python3-function-invoker/blob/master/samples/concat/concat.py

The 500 response is cryptic though. Does the riff team have a recommended approach for handling errored functions?

**Comment by matthewmcnew** [comment]
I added a commit that will return a more descriptive error with a 500 response. 

Something like:
> Error Invoking Function: AttributeError("'dict' object has no attribute 'upper'")

**Comment by fbiville** [comment]
Now merged, thank you!

**Comment by fbiville** [comment]
Now merged, thank you!

**Comment by fbiville** [comment]
Now merged, thank you

**Comment by fbiville** [comment]
Now merged, thank you!

**Comment by fbiville** [comment]
Now merged, thank you!

**Pull request closed without merging**
